name: 'Proto Compile'
description: 'A GitHub Action for generating code from Protocol Buffers (.proto) files, supporting languages like Go, Python, and TypeScript'

inputs:
  version:
    description: 'Version for tagging'
    required: true

  stable-mode: 
    description: "Optional: markdown format"
    required: false
    default: 'true'


runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }} 
    - name: Proto Dependencies
      run: 
        dependent-proto.sh
      shell: bash
    - name: Proto Compile
      run: 
        compile.sh
      shell: bash
      env:
        TAG_VERSION: ${{ inputs.version }}
    - name: Format Doc
      run: |
        echo "STABLE_MODE = $STABLE_MODE"
        if [ "$STABLE_MODE" == 'false' ]; then
          sudo -E TAG_VERSION=$TAG_VERSION curl -sL "https://raw.githubusercontent.com/lctech-andychuang/protobuf-codegen-action/main/proto/md-formatter.sh" | bash -s -- --remove-toc
        else
          sudo -E TAG_VERSION=$TAG_VERSION curl -sL "https://raw.githubusercontent.com/lctech-andychuang/protobuf-codegen-action/main/proto/md-formatter.sh" | bash
        fi
      shell: bash
      env:
        TAG_VERSION: ${{ inputs.version }}
        STABLE_MODE: ${{ inputs.stable-mode }}