name: 'Protofub Gen'
description: 'A GitHub Action for generating code from Protocol Buffers (.proto) files, supporting languages like Go, Python, and TypeScript'

inputs:
  name:
    description: 'Your name'
    required: true
    default: 'my friend'
  greeting:
    description: 'Custom greeting message'
    default: 'Hello'

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }} 
    - name: Proto Compile
      run: compile.sh
      shell: bash