name: 'Proto Compile'
description: 'A GitHub Action for generating code from Protocol Buffers (.proto) files, supporting languages like Go, Python, and TypeScript'

inputs:
  version:
    description: 'Version for tagging'
    required: true
  args-md-formatter:
    default: ''
    description: 'Arguments for md-formatter.sh'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }} 
    - name: Proto Dependencies
      run: 
        dependent-proto.sh
      shell: bash
    - name: Proto Compile
      run: 
        TAG_VERSION="v${TAG_VERSION}" compile.sh
      shell: bash
      env:
        TAG_VERSION: ${{ inputs.version }}
    - name: Format Doc
      run: 
        sudo -E TAG_VERSION=$TAG_VERSION curl -sL "https://raw.githubusercontent.com/lctech-andychuang/protobuf-codegen-action/main/proto/md-formatter.sh" | bash -s -- $ARGS 
      shell: bash
      env:
        TAG_VERSION: ${{ inputs.version }}
        ARGS: ${{ inputs.args-md-formatter }}