name: 'Proto Compile'
description: 'A GitHub Action for generating code from Protocol Buffers (.proto) files, supporting languages like Go, Python, and TypeScript'

inputs:
  version:
    description: 'Your name'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }} 
    - name: Proto Dependencies
      run: 
        dependent-proto.sh
      shell: bash
    - name: Proto Compile
      run: 
        TAG_VERSION="v${TAG_VERSION}" compile.sh
      shell: bash
      env:
        TAG_VERSION: ${{ inputs.version }}