name: 'Proto Compile'
description: 'A GitHub Action for generating code from Protocol Buffers (.proto) files, supporting languages like Go, Python, and TypeScript'

inputs:
  version:
    description: 'Version for tagging'
    required: true

  stable-mode: 
    description: "Optional: markdown format"
    required: false
    default: 'true'

  compile-mode:
    description: "Optional: compile mode"
    required: true
    default: 'neo'

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }} 
        
    - name: Proto Dependencies
      run: 
        ./proto/dependent-proto.sh
      shell: bash

    - name: Proto Compile
      run: 
        COMPILE_MODE=$COMPILE_MODE ./proto/compile.sh
      shell: bash
      env:
        TAG_VERSION: ${{ inputs.version }}
        COMPILE_MODE: ${{ inputs.compile-mode }}

    - name: Format Doc
      run: |
        echo "STABLE_MODE = $STABLE_MODE"
        if [ "$STABLE_MODE" == 'false' ]; then
          sudo -E TAG_VERSION=$TAG_VERSION curl -sL "https://raw.githubusercontent.com/lctech-tw/protobuf-codegen-action/main/proto/md-formatter.sh" | bash -s -- --remove-toc
        else
          sudo -E TAG_VERSION=$TAG_VERSION curl -sL "https://raw.githubusercontent.com/lctech-tw/protobuf-codegen-action/main/proto/md-formatter.sh" | bash
        fi
      shell: bash
      env:
        TAG_VERSION: ${{ inputs.version }}
        STABLE_MODE: ${{ inputs.stable-mode }}

    # md-formatter.sh was committed in the repo by previous way
    - name: Remove md-formatter.sh
      run: |
        sudo rm -f md-formatter.sh
        sudo rm -f md-formater.sh
        sudo rm -f md-formator.sh
        sudo rm -f md-formattor.sh
      shell: bash