name: Bug
description: File a bug issue
title: "[Bug]: <Please Replace with a Summary of the Bug> "
labels: ["bug", "p2", "needs triage"]
body:
  - type: markdown
    attributes:
      value: >
        Thank you so much for taking the time to fill out this bug report!
        
        **Please note: any issue that is currently affecting your production should be directed to Google Cloud customer support.*
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please share what you expected and what happened!
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. In case of exceptions, please paste the entire stacktrace.
      render: shell
